#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin $Script);
use XML::Simple;
use WWW::Mechanize;
use LWP::UserAgent;
use Data::Dumper;

die "Syntax: $Script <sourcedir>" unless @ARGV == 1;
my ($sourcedir) = @ARGV;
die "Source directory invalid: $sourcedir" unless -d $sourcedir;

my $metaFile = "$sourcedir/meta.xml";
die "Unable to find $metaFile" unless -f $metaFile;

my $meta = XMLin($metaFile, KeyAttr=>['id'], ForceArray=>['image']);

for my $id (keys %{$meta->{item}}) {
	my $item = $meta->{item}{$id};
	
	for my $f (qw'owner acquired url type category title') {
		die "Missing or empty field: $f for $id" unless $item->{$f};		
	}
	
	# Get $url to check that it returns 404 right now.
	
	# Upload all the images as $id-0.jpeg $id-1.jpeg and so on
	my @images;
		
	# Create wiki page with the correct name.
	
	# Create redirect page at $url to page. 	
	
}

